<a href="https://colab.research.google.com/github/nemalikantikrish/Python-mini-project-1/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive

In [ ]:
# mount the drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# read file from the drive
import pandas as pd

In [ ]:
datasetpath = '/content/drive/MyDrive/retail_transactions.csv'

In [ ]:
df=pd.read_csv(datasetpath)

In [ ]:
df

,TransactionID,TransactionDate,StoreID,CustomerID,ProductID,ProductCategory,Quantity,Price,PaymentType,Discount
0,T001,2024-01-01,102,1646,545,Electronics,1,150,Credit,15.0
1,T002,2024-01-02,103,1226,542,Toys,2,317,Debit,10.0
2,T003,2024-01-03,102,1515,593,Electronics,5,165,Debit,NaN
3,T004,2024-01-04,103,1793,560,Furniture,6,496,Debit,10.0
4,T005,2024-01-05,105,1864,523,Grocery,10,166,Debit,0.0
...,...,...,...,...,...,...,...,...,...,...
95,T096,2024-04-05,101,1918,559,Apparel,2,439,Cash,10.0
96,T097,2024-04-06,104,1190,579,Electronics,4,52,Debit,0.0
97,T098,2024-04-07,102,1932,504,Apparel,7,151,Credit,10.0
98,T099,2024-04-08,103,1285,587,Apparel,5,479,Credit,10.0
99,T100,2024-04-09,101,1602,574,Electronics,5,247,Credit,15.0

In [ ]:
df['TransactionDate'] = pd.to_datetime(df['TransactionDate'])

In [ ]:

df

,TransactionID,TransactionDate,StoreID,CustomerID,ProductID,ProductCategory,Quantity,Price,PaymentType,Discount
0,T001,2024-01-01,102,1646,545,Electronics,1,150,Credit,15.0
1,T002,2024-01-02,103,1226,542,Toys,2,317,Debit,10.0
2,T003,2024-01-03,102,1515,593,Electronics,5,165,Debit,NaN
3,T004,2024-01-04,103,1793,560,Furniture,6,496,Debit,10.0
4,T005,2024-01-05,105,1864,523,Grocery,10,166,Debit,0.0
...,...,...,...,...,...,...,...,...,...,...
95,T096,2024-04-05,101,1918,559,Apparel,2,439,Cash,10.0
96,T097,2024-04-06,104,1190,579,Electronics,4,52,Debit,0.0
97,T098,2024-04-07,102,1932,504,Apparel,7,151,Credit,10.0
98,T099,2024-04-08,103,1285,587,Apparel,5,479,Credit,10.0
99,T100,2024-04-09,101,1602,574,Electronics,5,247,Credit,15.0

In [ ]:
print("First 15 rows of the DataFrame:")

print(df.head(15))

First 15 rows of the DataFrame:
   TransactionID TransactionDate  StoreID  CustomerID  ProductID  \
0           T001      2024-01-01      102        1646        545
1           T002      2024-01-02      103        1226        542
2           T003      2024-01-03      102        1515        593
3           T004      2024-01-04      103        1793        560
4           T005      2024-01-05      105        1864        523
5           T006      2024-01-06      103        1836        515
6           T007      2024-01-07      103        1983        586
7           T008      2024-01-08      101        1806        569
8           T009      2024-01-09      101        1925        548
9           T010      2024-01-10      101        1711        565
10          T011      2024-01-11      103        1276        565
11          T012      2024-01-12      101        1486        523
12          T013      2024-01-13      103        1597        516
13          T014      2024-01-14      101        1462        520
14          T015      2024-01-15      104        1668        581

   ProductCategory  Quantity  Price PaymentType  Discount
0      Electronics         1    150      Credit      15.0
1             Toys         2    317       Debit      10.0
2      Electronics         5    165       Debit       NaN
3        Furniture         6    496       Debit      10.0
4          Grocery        10    166       Debit       0.0
5          Grocery         9    227       Debit       NaN
6      Electronics         1    170      Credit       NaN
7             Toys         4    500       Debit       0.0
8          Apparel         7    217        Cash      10.0
9        Furniture         3    466       Debit       5.0
10       Furniture         1    321        Cash       NaN
11            Toys         8    426      Credit       5.0
12            Toys         5    262        Cash      15.0
13     Electronics        10    218        Cash       NaN
14            Toys         4    201       Debit      15.0

In [ ]:
print("\nDataFrame Description:")

print(df.describe())

DataFrame Description:
           TransactionDate     StoreID   CustomerID   ProductID    Quantity  \
count                  100  100.000000   100.000000  100.000000  100.000000
mean   2024-02-19 12:00:00  102.730000  1552.520000  554.390000    5.370000
min    2024-01-01 00:00:00  101.000000  1013.000000  501.000000    1.000000
25%    2024-01-25 18:00:00  101.000000  1310.250000  529.750000    3.000000
50%    2024-02-19 12:00:00  103.000000  1534.000000  554.000000    5.500000
75%    2024-03-15 06:00:00  104.000000  1800.750000  579.500000    8.000000
max    2024-04-09 00:00:00  105.000000  1983.000000  600.000000   10.000000
std                    NaN    1.384291   268.295461   28.544098    3.013957

           Price   Discount
count  100.00000  75.000000
mean   282.15000   7.733333
min     50.00000   0.000000
25%    165.75000   2.500000
50%    280.00000  10.000000
75%    415.25000  12.500000
max    500.00000  15.000000
std    140.19938   5.652871

In [ ]:
print("\nMissing values per column:")

print(df.isnull().sum())

Missing values per column:
TransactionID       0
TransactionDate     0
StoreID             0
CustomerID          0
ProductID           0
ProductCategory     0
Quantity            0
Price               0
PaymentType         0
Discount           25
dtype: int64

In [ ]:
df['Discount'] = df['Discount'].fillna(8)

In [ ]:
print("\nMissing values after filling Discount:")
print(df['Discount'].isnull().sum())

Missing values after filling Discount:
0

In [ ]:
df['NetPrice'] = df['Price'] * (1 - df['Discount'] / 100)

In [ ]:
df['TotalSale'] = df['Quantity']

df['NetPrice']
df['NetPrice']

0     127.50
1     285.30
2     151.80
3     446.40
4     166.00
       ...
95    395.10
96     52.00
97    135.90
98    431.10
99    209.95
Name: NetPrice, Length: 100, dtype: float64

In [ ]:
print("\nDataFrame with new NetPrice and TotalSale columns:")

print(df.head())

DataFrame with new NetPrice and TotalSale columns:
  TransactionID TransactionDate  StoreID  CustomerID  ProductID  \
0          T001      2024-01-01      102        1646        545
1          T002      2024-01-02      103        1226        542
2          T003      2024-01-03      102        1515        593
3          T004      2024-01-04      103        1793        560
4          T005      2024-01-05      105        1864        523

  ProductCategory  Quantity  Price PaymentType  Discount  NetPrice  TotalSale
0     Electronics         1    150      Credit      15.0     127.5          1
1            Toys         2    317       Debit      10.0     285.3          2
2     Electronics         5    165       Debit       8.0     151.8          5
3       Furniture         6    496       Debit      10.0     446.4          6
4         Grocery        10    166       Debit       0.0     166.0         10

In [ ]:
filtered_df = df[df['TotalSale'] >= 20].copy()

In [ ]:
filtered_df

Empty DataFrame
Columns: [TransactionID, TransactionDate, StoreID, CustomerID, ProductID, ProductCategory, Quantity, Price, PaymentType, Discount, NetPrice, TotalSale]
Index: []

In [ ]:
df

,TransactionID,TransactionDate,StoreID,CustomerID,ProductID,ProductCategory,Quantity,Price,PaymentType,Discount,NetPrice,TotalSale
0,T001,2024-01-01,102,1646,545,Electronics,1,150,Credit,15.0,127.50,1
1,T002,2024-01-02,103,1226,542,Toys,2,317,Debit,10.0,285.30,2
2,T003,2024-01-03,102,1515,593,Electronics,5,165,Debit,8.0,151.80,5
3,T004,2024-01-04,103,1793,560,Furniture,6,496,Debit,10.0,446.40,6
4,T005,2024-01-05,105,1864,523,Grocery,10,166,Debit,0.0,166.00,10
...,...,...,...,...,...,...,...,...,...,...,...,...
95,T096,2024-04-05,101,1918,559,Apparel,2,439,Cash,10.0,395.10,2
96,T097,2024-04-06,104,1190,579,Electronics,4,52,Debit,0.0,52.00,4
97,T098,2024-04-07,102,1932,504,Apparel,7,151,Credit,10.0,135.90,7
98,T099,2024-04-08,103,1285,587,Apparel,5,479,Credit,10.0,431.10,5
99,T100,2024-04-09,101,1602,574,Electronics,5,247,Credit,15.0,209.95,5

In [ ]:
print("\nShape of the filtered DataFrame:")

print(filtered_df.shape)

Shape of the filtered DataFrame:
(0, 12)

In [ ]:

filtered_df = df[df['TotalSale'] >= 20].copy()

In [ ]:
print("\nData types after converting Payment Type to category:")

print(filtered_df.dtypes)

Data types after converting Payment Type to category:
TransactionID              object
TransactionDate    datetime64[ns]
StoreID                     int64
CustomerID                  int64
ProductID                   int64
ProductCategory            object
Quantity                    int64
Price                       int64
PaymentType                object
Discount                  float64
NetPrice                  float64
TotalSale                 float64
dtype: object

In [ ]:
grouped = filtered_df.groupby('ProductCategory').agg(TotalQuantity=('Quantity', 'sum'), TotalSale=('TotalSale', 'sum'))

In [ ]:
filtered_df.groupby

<bound method DataFrame.groupby of    TransactionID TransactionDate  StoreID  CustomerID  ProductID  \
0           T001      2024-01-01      102        1646        545
1           T002      2024-01-02      103        1226        542
2           T003      2024-01-03      102        1515        593
3           T004      2024-01-04      103        1793        560
4           T005      2024-01-05      105        1864        523
..           ...             ...      ...         ...        ...
95          T096      2024-04-05      101        1918        559
96          T097      2024-04-06      104        1190        579
97          T098      2024-04-07      102        1932        504
98          T099      2024-04-08      103        1285        587
99          T100      2024-04-09      101        1602        574

   ProductCategory  Quantity  Price PaymentType  Discount  NetPrice  TotalSale
0      Electronics         1    150      Credit      15.0    127.50     127.50
1             Toys         2    317       Debit      10.0    285.30     570.60
2      Electronics         5    165       Debit       8.0    151.80     759.00
3        Furniture         6    496       Debit      10.0    446.40    2678.40
4          Grocery        10    166       Debit       0.0    166.00    1660.00
..             ...       ...    ...         ...       ...       ...        ...
95         Apparel         2    439        Cash      10.0    395.10     790.20
96     Electronics         4     52       Debit       0.0     52.00     208.00
97         Apparel         7    151      Credit      10.0    135.90     951.30
98         Apparel         5    479      Credit      10.0    431.10    2155.50
99     Electronics         5    247      Credit      15.0    209.95    1049.75

[100 rows x 12 columns]>

In [ ]:
grouped = grouped.sort_values(by='TotalSale', ascending=False)

In [ ]:
grouped_sorted = grouped.sort_values(by='TotalSale', ascending=False) # Assign the result of sort_values to grouped_sorted
grouped_sorted

                 TotalQuantity  TotalSale
ProductCategory
Toys                       137   43470.91
Furniture                  130   38143.71
Apparel                    117   27827.35
Grocery                     75   17343.08
Electronics                 78   15173.85

In [ ]:
print("\nGrouped and sorted by TotalSale:")

print(grouped_sorted)

Grouped and sorted by TotalSale:
                 TotalQuantity  TotalSale
ProductCategory
Toys                       137   43470.91
Furniture                  130   38143.71
Apparel                    117   27827.35
Grocery                     75   17343.08
Electronics                 78   15173.85

In [ ]:


top_3_categories = grouped_sorted.head(3)

print("\nTop 3 product categories with the highest total sales:")

print(top_3_categories)

Top 3 product categories with the highest total sales:
                 TotalQuantity  TotalSale
ProductCategory
Toys                       137   43470.91
Furniture                  130   38143.71
Apparel                    117   27827.35

In [ ]:
multi = filtered_df.groupby(["StoreID", 'ProductCategory'])['TotalSale'].mean().reset_index()

multi

    StoreID ProductCategory    TotalSale
0       101         Apparel  1344.550000
1       101     Electronics  1070.783333
2       101       Furniture  1300.923750
3       101            Toys  2196.865556
4       102         Apparel  1406.580000
5       102     Electronics   578.180000
6       102       Furniture  2425.140000
7       102         Grocery   171.900000
8       102            Toys  1008.888571
9       103         Apparel  1021.950000
10      103     Electronics   752.253333
11      103       Furniture  1501.697143
12      103         Grocery   913.990000
13      103            Toys  1239.180000
14      104         Apparel   722.000000
15      104     Electronics   852.333333
16      104       Furniture  1431.694286
17      104         Grocery  1092.406667
18      104            Toys  1367.700000
19      105         Apparel  2398.450000
20      105     Electronics  2128.420000
21      105       Furniture  1176.150000
22      105         Grocery  2047.600000
23      105            Toys  3852.800000

In [ ]:
multi_grouped = multi.rename(columns={'TotalSale': 'AvgTotalSale'})  # Assign the result of rename to multi_grouped

In [ ]:
print("\nMulti-level grouping by StoreID and Product Category with average TotalSale:")

print(multi_grouped)

Multi-level grouping by StoreID and Product Category with average TotalSale:
    StoreID ProductCategory  AvgTotalSale
0       101         Apparel   1344.550000
1       101     Electronics   1070.783333
2       101       Furniture   1300.923750
3       101            Toys   2196.865556
4       102         Apparel   1406.580000
5       102     Electronics    578.180000
6       102       Furniture   2425.140000
7       102         Grocery    171.900000
8       102            Toys   1008.888571
9       103         Apparel   1021.950000
10      103     Electronics    752.253333
11      103       Furniture   1501.697143
12      103         Grocery    913.990000
13      103            Toys   1239.180000
14      104         Apparel    722.000000
15      104     Electronics    852.333333
16      104       Furniture   1431.694286
17      104         Grocery   1092.406667
18      104            Toys   1367.700000
19      105         Apparel   2398.450000
20      105     Electronics   2128.420000
21      105       Furniture   1176.150000
22      105         Grocery   2047.600000
23      105            Toys   3852.800000

In [ ]:
multi_grouped = filtered_df.groupby(['StoreID', 'ProductCategory'])['TotalSale'].mean().reset_index()
multi_grouped = multi_grouped.rename(columns={'TotalSale': 'AvgTotalSale'})
sorted_grouped = multi_grouped.sort_values(['StoreID', 'AvgTotalSale'], ascending=[True, False])

In [ ]:
top_categories_per_store=sorted_grouped.groupby('StoreID').first().reset_index()

In [ ]:

# summary = df.groupby('storeID').apply(lambda x: x.nlargest(1, 'AvgTotalSale'))[['storeID', 'ProductCategory', "AvgTotalSale"]]

In [ ]:
summary_df = top_categories_per_store[['StoreID','ProductCategory','AvgTotalSale']]  # Corrected column names to match the DataFrame

In [ ]:
Summary_df

   StoreID ProductCategory  AvgTotalSale
0      101            Toys   2196.865556
1      102       Furniture   2425.140000
2      103       Furniture   1501.697143
3      104       Furniture   1431.694286
4      105            Toys   3852.800000

In [ ]:
print("\nSummary DataFrame with top ProductCategory and average TotalSale for each store:")

print(summary_df)

Summary DataFrame with top ProductCategory and average TotalSale for each store:
   StoreID ProductCategory  AvgTotalSale
0      101            Toys   2196.865556
1      102       Furniture   2425.140000
2      103       Furniture   1501.697143
3      104       Furniture   1431.694286
4      105            Toys   3852.800000